In [58]:
from dotenv import load_dotenv
load_dotenv()

True

In [59]:
import os
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
GOOGLE_URL = "https://www.googleapis.com/books/v1/volumes"

In [60]:
import requests
import pandas as pd

df = pd.read_csv("file.csv").head()
df

,title,author,isbn,pages,publication_year,rating,reviews_count,price,currency,age_restriction,genres,publisher,formats,url,price_numeric,rating_numeric,pages_numeric,reviews_numeric
0,Проект «Холодное сердце»,Татьяна Дубинина,NaN,120.0,2026.0,5.0,7.0,139.0,RUB,16+,"Короткие любовные романы, Литрес Авторы, Служе...",Правообладатель: Автор,"epub,, fb2,, fb3,, ios.epub,, mobi,, pdf,, txt...",https://www.litres.ru//book/tatyana-dubinina-3...,139.0,5.0,120.0,7.0
1,"Там, где мы настоящие",Инма Рубиалес,9785006318250,609.0,2024.0,4.6,10.0,399.0,RUB,18+,"Young adult, Внутренняя гармония, Зарубежные л...",Правообладатель: Альпина Диджитал,"epub,, fb2,, fb3,, mobi,, pdf,, txt,, zip",https://www.litres.ru//book/inma-rubiales-3324...,399.0,4.6,609.0,10.0
2,Маленькая хозяйка большой кухни-3,Наталья Лакота,NaN,310.0,2026.0,5.0,33.0,199.0,RUB,16+,"Бытовое фэнтези, Историческое фэнтези, Литрес ...",Правообладатель: Автор,"epub,, fb2,, fb3,, ios.epub,, mobi,, pdf,, txt...",https://www.litres.ru//book/natalya-lakota/mal...,199.0,5.0,310.0,33.0
3,Перси Джексон и проклятие титана,Рик Риордан,978-5-04-150876-0,270.0,2007.0,4.9,450.0,329.0,RUB,12+,"Героическое фэнтези, Древние боги, Зарубежное ...",Правообладатель: Эксмо,"epub,, fb2,, fb3,, ios.epub,, mobi,, pdf,, txt...",https://www.litres.ru//book/rik-riordan/persi-...,329.0,4.9,270.0,450.0
4,Личный аптекарь императора. Том 7,"Сергей Карелин,",NaN,6.0,2025.0,4.9,48.0,299.0,RUB,16+,"Алхимия, Альтернативная история, Аномальные зо...","Правообладатели: Автор, Аудио от автора","m4b,, mp3,, zip",https://www.litres.ru//audiobook/sergey-kareli...,299.0,4.9,6.0,48.0

In [61]:
def search_book(title, author):
    responce = requests.get(GOOGLE_URL, params={"q": f"intitle:{title}+inauthor:{author}", "maxResults": 5, "key": GOOGLE_API_KEY})
    return responce.json()

In [62]:
search_book("Маленькая хозяйка большой кухни-3", "Наталья Лакота")

{'kind': 'books#volumes',
 'totalItems': 2,
 'items': [{'kind': 'books#volume',
   'id': 'DI-4EQAAQBAJ',
   'etag': 'IkY+eDn7dAE',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/DI-4EQAAQBAJ',
   'volumeInfo': {'title': 'Маленькая хозяйка большой кухни-3',
    'authors': ['Наталья Лакота'],
    'publisher': 'ЛитРес, SelfPub',
    'publishedDate': '2026-01-26',
    'description': 'Третья и заключительная история про Сесилию Лайон – маленькую хозяйку королевской кухни. Сесилия назначена инспектрисой королевской кухни, Ричард де Морвиль снова занял должность маршала при дворе, и всё складывается как нельзя лучше. Но вдруг снова тревожно звучит колокол. На этот раз... свадебный.',
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9785048628386'},
     {'type': 'ISBN_10', 'identifier': '5048628381'}],
    'readingModes': {'text': True, 'image': True},
    'pageCount': 346,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': False,
    'contentVersion': '1.1.1.0.preview.3',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=DI-4EQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=DI-4EQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
    'language': 'ru',
    'previewLink': 'http://books.google.ru/books?id=DI-4EQAAQBAJ&printsec=frontcover&dq=intitle:%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F+%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D0%BA%D0%B0+%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B9+%D0%BA%D1%83%D1%85%D0%BD%D0%B8-3%2Binauthor:%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%8C%D1%8F+%D0%9B%D0%B0%D0%BA%D0%BE%D1%82%D0%B0&hl=&cd=1&source=gbs_api',
    'infoLink': 'https://play.google.com/store/books/details?id=DI-4EQAAQBAJ&source=gbs_api',
    'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=DI-4EQAAQBAJ'},
   'saleInfo': {'country': 'RU',
    'saleability': 'FOR_SALE',
    'isEbook': True,
    'listPrice': {'amount': 278.6, 'currencyCode': 'RUB'},
    'retailPrice': {'amount': 250.74, 'currencyCode': 'RUB'},
    'buyLink': 'https://play.google.com/store/books/details?id=DI-4EQAAQBAJ&rdid=book-DI-4EQAAQBAJ&rdot=1&source=gbs_api',
    'offers': [{'finskyOfferType': 1,
      'listPrice': {'amountInMicros': 278600000, 'currencyCode': 'RUB'},
      'retailPrice': {'amountInMicros': 250740000, 'currencyCode': 'RUB'}}]},
   'accessInfo': {'country': 'RU',
    'viewability': 'PARTIAL',
    'embeddable': True,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': True,
     'acsTokenLink': 'http://books.google.ru/books/download/%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F_%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D0%BA%D0%B0_%D0%B1%D0%BE%D0%BB-sample-epub.acsm?id=DI-4EQAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
    'pdf': {'isAvailable': True,
     'acsTokenLink': 'http://books.google.ru/books/download/%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F_%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D0%BA%D0%B0_%D0%B1%D0%BE%D0%BB-sample-pdf.acsm?id=DI-4EQAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
    'webReaderLink': 'http://play.google.com/books/reader?id=DI-4EQAAQBAJ&hl=&source=gbs_api',
    'accessViewStatus': 'SAMPLE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': 'Третья и заключительная история про Сесилию Лайон – маленькую хозяйку королевской кухни. Сесилия назначена инспектрисой ...'}},
  {'kind': 'books#volume',
   'id': 'DI-4EQAAQBAJ',
   'etag': 'dnCjrL2NIhw',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/DI-4EQAAQBAJ',
   'volumeInfo': {'title': 'Маленькая хозяйка большой кухни-3',
    'authors': ['Наталья Лакота'],
    'publisher': 'ЛитРес, SelfPub',
    'publishedDate': '2026-01-26',
    'description': 'Третья и заключительная история про Сесилию Лайон – маленькую хозяйку королевской кухни. Сесилия назначена инспектрисой королевской кухни, Ричард де Морвиль снова занял должность маршала при дворе, и всё складывается как нельзя лучше. Но вдруг снова тревожно звучит колокол. На этот раз... свадебный.',
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9785048628386'},
     {'type': 'ISBN_10', 'identifier': '5048628381'}],
    'readingModes': {'text': True, 'image': True},
    'pageCount': 346,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': False,
    'contentVersion': '1.1.1.0.preview.3',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=DI-4EQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=DI-4EQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
    'language': 'ru',
    'previewLink': 'http://books.google.ru/books?id=DI-4EQAAQBAJ&pg=PP1&dq=intitle:%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F+%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D0%BA%D0%B0+%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B9+%D0%BA%D1%83%D1%85%D0%BD%D0%B8-3%2Binauthor:%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%8C%D1%8F+%D0%9B%D0%B0%D0%BA%D0%BE%D1%82%D0%B0&hl=&cd=2&source=gbs_api',
    'infoLink': 'https://play.google.com/store/books/details?id=DI-4EQAAQBAJ&source=gbs_api',
    'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=DI-4EQAAQBAJ'},
   'saleInfo': {'country': 'RU',
    'saleability': 'FOR_SALE',
    'isEbook': True,
    'listPrice': {'amount': 278.6, 'currencyCode': 'RUB'},
    'retailPrice': {'amount': 250.74, 'currencyCode': 'RUB'},
    'buyLink': 'https://play.google.com/store/books/details?id=DI-4EQAAQBAJ&rdid=book-DI-4EQAAQBAJ&rdot=1&source=gbs_api',
    'offers': [{'finskyOfferType': 1,
      'listPrice': {'amountInMicros': 278600000, 'currencyCode': 'RUB'},
      'retailPrice': {'amountInMicros': 250740000, 'currencyCode': 'RUB'}}]},
   'accessInfo': {'country': 'RU',
    'viewability': 'PARTIAL',
    'embeddable': True,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': True,
     'acsTokenLink': 'http://books.google.ru/books/download/%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F_%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D0%BA%D0%B0_%D0%B1%D0%BE%D0%BB-sample-epub.acsm?id=DI-4EQAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
    'pdf': {'isAvailable': True,
     'acsTokenLink': 'http://books.google.ru/books/download/%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F_%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D0%BA%D0%B0_%D0%B1%D0%BE%D0%BB-sample-pdf.acsm?id=DI-4EQAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
    'webReaderLink': 'http://play.google.com/books/reader?id=DI-4EQAAQBAJ&hl=&source=gbs_api',
    'accessViewStatus': 'SAMPLE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': 'Наталья <b>Лакота</b>. Наталья <b>Лакота</b> МАЛЕНЬКАЯ <b>ХОЗЯЙКА БОЛЬШОЙ КУХНИ - 3</b> Наталья <b>Лакота</b> Маленькая <b>хозяйка большой кухни-3</b>. Front Cover.'}}]}

In [63]:
def search_correct_book(title, author):
    all_books = search_book(title, author)
    if not all_books.get('items'):
        return None, None, None, None, None, None, None, None, None, None, None, None, None, None, None
    
    first_book = all_books['items'][0]
    id_book = first_book['id']
    categories = first_book.get('volumeInfo', dict()).get('categories', None)
    publisher = first_book.get('volumeInfo', dict()).get('publisher', None)
    description = first_book.get('volumeInfo', dict()).get('description', None)
    print_type = first_book.get('volumeInfo', dict()).get('print_type', None)
    country = first_book.get('saleInfo', dict()).get('country', None)
    saleability = first_book.get('saleInfo', dict()).get('saleability', None)
    isEbook = first_book.get('saleInfo', dict()).get('isEbook', None)
    listPrice = first_book.get('saleInfo', dict()).get('listPrice', dict()).get('amount', None)
    currencyCode = first_book.get('saleInfo', dict()).get('listPrice', dict()).get('currencyCode', None)
    publicDomain = first_book.get('accessInfo', dict()).get('publicDomain', None)
    epub_avaliable = first_book.get('accessInfo', dict()).get('epub', dict()).get('isAvailable', None)
    pdf_avaliable = first_book.get('accessInfo', dict()).get('pdf', dict()).get('isAvailable', None)
    viewability = first_book.get('accessInfo', dict()).get('viewability', None)
    snippet = first_book.get('searchInfo', dict()).get('snippet', None)
    return id_book, categories, publisher, description, print_type, country, saleability, isEbook, listPrice, currencyCode, viewability, publicDomain, epub_avaliable, pdf_avaliable, snippet

In [64]:
search_correct_book("Маленькая хозяйка большой кухни-3", "Наталья Лакота")

('DI-4EQAAQBAJ',
 ['Fiction'],
 'ЛитРес, SelfPub',
 'Третья и заключительная история про Сесилию Лайон – маленькую хозяйку королевской кухни. Сесилия назначена инспектрисой королевской кухни, Ричард де Морвиль снова занял должность маршала при дворе, и всё складывается как нельзя лучше. Но вдруг снова тревожно звучит колокол. На этот раз... свадебный.',
 None,
 'RU',
 'FOR_SALE',
 True,
 278.6,
 'RUB',
 'PARTIAL',
 False,
 True,
 True,
 None)

In [65]:
df[['id_book', 'categories', 'publisher', 'description', 'print_type', 'country', 'saleability', 'isEbook', 'listPrice', 'currencyCode', 'viewability', 'publicDomain', 'epub_avaliable', 'pdf_avaliable', 'snippet']] = df.apply(lambda x: pd.Series(search_correct_book(x['title'], x['author'])), axis=1)

In [66]:
df

,title,author,isbn,pages,publication_year,rating,reviews_count,price,currency,age_restriction,...,country,saleability,isEbook,listPrice,currencyCode,viewability,publicDomain,epub_avaliable,pdf_avaliable,snippet
0,Проект «Холодное сердце»,Татьяна Дубинина,NaN,120.0,2026.0,5.0,7.0,139.0,RUB,16+,...,RU,FOR_SALE,True,194.6,RUB,PARTIAL,False,True,True,None
1,"Там, где мы настоящие",Инма Рубиалес,9785006318250,609.0,2024.0,4.6,10.0,399.0,RUB,18+,...,NaN,NaN,None,NaN,NaN,NaN,None,None,None,None
2,Маленькая хозяйка большой кухни-3,Наталья Лакота,NaN,310.0,2026.0,5.0,33.0,199.0,RUB,16+,...,RU,FOR_SALE,True,278.6,RUB,PARTIAL,False,True,True,None
3,Перси Джексон и проклятие титана,Рик Риордан,978-5-04-150876-0,270.0,2007.0,4.9,450.0,329.0,RUB,12+,...,RU,NOT_FOR_SALE,False,NaN,NaN,NO_PAGES,False,False,False,None
4,Личный аптекарь императора. Том 7,"Сергей Карелин,",NaN,6.0,2025.0,4.9,48.0,299.0,RUB,16+,...,NaN,NaN,None,NaN,NaN,NaN,None,None,None,None